# See https://www.mkdocs.org/user-guide/configuration/
# and https://squidfunk.github.io/mkdocs-material/reference/
site_name: WoW-TC
site_description: 'Short description'
site_author: 'Bloodmallet(EU)'
repo_url: https://github.com/Bloodmallet/wowtc
edit_uri: edit/main/docs/

theme: 
  name: material
  custom_dir: theme_overrides/
  features:
    - content.tabs.link
  language: en
  palette:
    scheme: slate
    primary: green
    accent: light green


markdown_extensions:
  # https://squidfunk.github.io/mkdocs-material/reference/#configuration
  - meta
  # https://squidfunk.github.io/mkdocs-material/reference/abbreviations/
  - abbr
  - pymdownx.snippets
  # https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/reference/annotations/
  - attr_list
  - md_in_html
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/reference/buttons/
  - attr_list
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # https://squidfunk.github.io/mkdocs-material/reference/content-tabs/
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # https://squidfunk.github.io/mkdocs-material/reference/data-tables/
  - tables
  # https://squidfunk.github.io/mkdocs-material/reference/diagrams/
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  # https://squidfunk.github.io/mkdocs-material/reference/footnotes/
  - footnotes
  # https://squidfunk.github.io/mkdocs-material/reference/formatting/
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # https://squidfunk.github.io/mkdocs-material/reference/grids/
  - attr_list
  - md_in_html
  # https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # https://squidfunk.github.io/mkdocs-material/reference/images/
  - attr_list
  - md_in_html
  # https://squidfunk.github.io/mkdocs-material/reference/lists/
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - pymdownx.arithmatex:
      generic: true
  # https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
  - toc:
      permalink: '#'

nav:
  - Home: index.md
  - Example: example.md
  - Contributing: contributing.md
  - Impressum: impressum.md

extra:
  footer_with_nav: false

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - theme_overrides
